services:
  # Backend Service
  - type: web
    name: hisabkitab-server
    env: node
    rootDir: server
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma db push && node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hisabkitab-db
          property: connectionString



databases:
  - name: hisabkitab-db
    databaseName: hisabkitab
    user: hisabkitab
    plan: free # Uses the free tier for PostgreSQL
