services:
  - type: web
    name: hisabkitab-server
    env: node
    rootDir: server
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma db push && node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hisabkitab-db
          property: connectionString

  - type: static
    name: hisabkitab-client
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: hisabkitab-server
          envVar: RENDER_EXTERNAL_URL

databases:
  - name: hisabkitab-db
    databaseName: hisabkitab
    user: hisabkitab
    plan: free
