services:
  # Backend Service
  - type: web
    name: hisabkitab-server
    env: node
    rootDir: server
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma db push && node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
